# qmake project generated by QMsDev
#
# General settings

TEMPLATE = lib
CONFIG  += warn_off staticlib create_prl
#TARGET  += UsefulMath

INCLUDEPATH += ../../

# Input

SOURCES =  \
		AreaVolumes.cpp \
		LinearAlgebra.cpp \
		Matrix.cpp \
		Quaternion.cpp \
		Ray.cpp \
		TrilinearGrid.cpp \
		Tuple.cpp \
		Vector.cpp

HEADERS =  \
		AreaVolumes.h \
		LinearAlgebra.h \
		Matrix.h \
		Quaternion.h \
		Ray.h \
		TrilinearGrid.h \
		Tuple.h \
		Vector.h

