# qmake project generated by QMsDev
#
# General settings

TEMPLATE = lib
CONFIG  += opengl warn_off staticlib create_prl
#TARGET  += Geometry

# Input
INCLUDEPATH += ../UsefulMath

SOURCES =  \
		Geometry.cpp \
		GeometryScene.cpp \
		GeometrySceneArray.cpp \
		IntQueue.cpp \
		MeshDerivatives.cpp \
		SceneArrayNode.cpp

HEADERS =  \
		Geometry.h \
		GeometryScene.h \
		GeometrySceneArray.h \
		IntQueue.h \
		MeshDerivatives.h \
		SceneArrayNode.h

