# qmake project generated by QMsDev
#
# General settings

TEMPLATE = lib
CONFIG  += warn_off staticlib create_prl
#TARGET  += ByteOrder

macx-g++ {
  QMAKE_CFLAGS += -m64
  QMAKE_CXXFLAGS += -m64
}

# Input

SOURCES =  \
		ByteSwapping.cpp

HEADERS =  \
		ByteSwapping.h

