# qmake project generated by QMsDev
#
# General settings

TEMPLATE = lib
CONFIG  += warn_off staticlib create_prl
#TARGET  += ByteOrder

# Input

SOURCES =  \
		ByteSwapping.cpp

HEADERS =  \
		ByteSwapping.h

