# qmake project generated by QMsDev
#
# General settings

TEMPLATE = lib
CONFIG  += warn_off staticlib create_prl
#TARGET  += VolumeFileTypes

macx-g++ {
  QMAKE_CFLAGS += -m64
  QMAKE_CXXFLAGS += -m64
}

# Input

INCLUDEPATH += ../ByteOrder
INCLUDEPATH += ../

SOURCES =  \
		DXFile.cpp \
		MRCFile.cpp \
		RawIVFile.cpp \
		RawVFile.cpp \
		VolumeFileType.cpp \
		VolumeLoader.cpp

HEADERS =  \
		DXFile.h \
		MRCFile.h \
		RawIVFile.h \
		RawVFile.h \
		VolumeFileType.h \
		VolumeLoader.h 


